In [1]:
import logging
import configparser
import os
from dask import dataframe as dd
import datetime as dt
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import lightgbm as lgb

# Data cleaning
import janitor

In [11]:
# Read config file
config = configparser.ConfigParser()
config.read("config.ini")

# Read parameters from config file
ROOT_DIR = config["FILES"]["ROOT_DIR"]
TRAIN = config["DATA"]["SUBSET_TRAINING_DATA"]
TEST = config["DATA"]["SUBSET_TEST_DATA"]

# Change working directory
os.chdir(ROOT_DIR)

In [12]:
raw = pd.read_parquet(TRAIN)

df = raw.copy()

In [15]:
df = df.clean_names()

# Change index name
df = df.rename_axis("id")

raw.head()

,srch_id,date_time,site_id,visitor_location_country_id,visitor_hist_starrating,visitor_hist_adr_usd,prop_country_id,prop_id,prop_starrating,prop_review_score,...,comp6_rate_percent_diff,comp7_rate,comp7_inv,comp7_rate_percent_diff,comp8_rate,comp8_inv,comp8_rate_percent_diff,click_bool,gross_bookings_usd,booking_bool
__null_dask_index__,,,,,,,,,,,,,,,,,,,,,
993,78,2012-12-21 05:30:35,5,205,NaN,NaN,15,9246,5,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
994,78,2012-12-21 05:30:35,5,205,NaN,NaN,15,10223,4,4.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
995,78,2012-12-21 05:30:35,5,205,NaN,NaN,15,16549,4,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
996,78,2012-12-21 05:30:35,5,205,NaN,NaN,15,31638,5,4.5,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0,NaN,0
997,78,2012-12-21 05:30:35,5,205,NaN,NaN,15,35509,5,4.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0